#!/usr/bin/env sh

NETBENCH=${NETBENCH:?must specify command line to launch NetBench}

parallel --line-buffer <<SIM
# Figure 7: pFabric: FCT statistics across different flow sizes in data mining workload
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/4000/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/4000/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/4000/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/4000/SPPIFO.properties'

    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/6000/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/6000/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/6000/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/6000/SPPIFO.properties'

    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/10000/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/10000/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/10000/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/10000/SPPIFO.properties'

    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/15000/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/15000/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/15000/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/15000/SPPIFO.properties'

    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/22500/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/22500/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/22500/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/22500/SPPIFO.properties'

    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/37000/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/37000/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/37000/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/37000/SPPIFO.properties'

    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/60000/DCTCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/60000/TCP.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/60000/PIFO.properties'
    ${NETBENCH} 'projects/sppifo/runs/sppifo_evaluation/pFabric/data_mining_workload/60000/SPPIFO.properties'
SIM

# Analyze and plot
python3 projects/sppifo/plots/sppifo_evaluation/pFabric/data_mining_workload/analyze.py
gnuplot projects/sppifo/plots/sppifo_evaluation/pFabric/data_mining_workload/plot.gnuplot
